const ADD_CREDIT_CARD_DETAILS_REQUEST = "ADD_CREDIT_CARD_DETAILS_REQUEST"
const ADD_CREDIT_CARD_DETAILS_SUCCESS = "ADD_CREDIT_CARD_DETAILS_SUCCESS"
const ADD_CREDIT_CARD_DETAILS_FAILURE = "ADD_CREDIT_CARD_DETAILS_FAILURE"

const GET_CREDIT_CARD_DETAILS_REQUEST = "GET_CREDIT_CARD_DETAILS_REQUEST"
const GET_CREDIT_CARD_DETAILS_SUCCESS = "GET_CREDIT_CARD_DETAILS_SUCCESS"
const GET_CREDIT_CARD_DETAILS_FAILURE = "GET_CREDIT_CARD_DETAILS_FAILURE"

const DELETE_CREDIT_CARD_DETAILS_REQUEST = "DELETE_CREDIT_CARD_DETAILS_REQUEST"
const DELETE_CREDIT_CARD_DETAILS_SUCCESS = "DELETE_CREDIT_CARD_DETAILS_SUCCESS"
const DELETE_CREDIT_CARD_DETAILS_FAILURE = "DELETE_CREDIT_CARD_DETAILS_FAILURE"

export default {
    ADD_CREDIT_CARD_DETAILS_REQUEST,
    ADD_CREDIT_CARD_DETAILS_SUCCESS,
    ADD_CREDIT_CARD_DETAILS_FAILURE,
    GET_CREDIT_CARD_DETAILS_REQUEST,
    GET_CREDIT_CARD_DETAILS_SUCCESS,
    GET_CREDIT_CARD_DETAILS_FAILURE,
    DELETE_CREDIT_CARD_DETAILS_REQUEST,
    DELETE_CREDIT_CARD_DETAILS_SUCCESS,
    DELETE_CREDIT_CARD_DETAILS_FAILURE
}