const USER_CREDIT_CARD_REQUEST = "USER_CREDIT_CARD_REQUEST"
const USER_CREDIT_CARD_SUCCESS = "USER_CREDIT_CARD_SUCCESS"
const USER_CREDIT_CARD_FAILURE = "USER_CREDIT_CARD_FAILURE"

export default {
    USER_CREDIT_CARD_REQUEST,
    USER_CREDIT_CARD_SUCCESS,
    USER_CREDIT_CARD_FAILURE
}